name: Speed Up CI with Cache

on:
  push:
    branches:
      - main

jobs:
  cache-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up cache
        uses: actions/cache@v4
        id: cache-step
        with:
          path: ~/.cache/pip
          key: cache-223337d
        
      - name: 23f3002872@ds.study.iitm.ac.in
        run: echo "Hello, world!"

      - name: prime-cache-223337d
        run: |
          echo "Cache hit: ${{ steps.cache-step.outputs.cache-hit }}"